<?php

use HAWMS\http\RequestFactory;

class RequestFactoryTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var RequestFactory
     */
    private $requestFactory;

    protected function setUp()
    {
        $_SERVER['SCRIPT_NAME'] = '/index.php';
        $_SERVER['REQUEST_URI'] = '/';

        $this->requestFactory = new RequestFactory();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $_GET = [];
        $_POST = [];
    }

    public function testShouldSetParams()
    {
        $_GET['foo'] = 'bar';
        $request = $this->requestFactory->createRequest();

        $this->assertNotNull($request);
        $this->assertSame($_GET, $request->getParams());
    }

    public function testShouldSetBody()
    {
        $_POST['foo'] = 'bar';
        $request = $this->requestFactory->createRequest();

        $this->assertNotNull($request);
        $this->assertSame($_POST, $request->getBody());
    }

    public function testShouldSetRequestMethod()
    {
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $request = $this->requestFactory->createRequest();

        $this->assertNotNull($request);
        $this->assertSame('POST', $request->getMethod());
    }

    public function testShouldSetUri()
    {
        $_SERVER['SCRIPT_NAME'] = '/project-1/index.php';
        $_SERVER['REQUEST_URI'] = '/project-1/course/1?fields=name';

        $request = $this->requestFactory->createRequest();

        $this->assertEquals('/course/1', $request->getUri());
    }
}
